server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${wp.datasource.driver-class-name}
      url: jdbc:mysql://${wp.datasource.host}:${wp.datasource.port}/${wp.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${wp.datasource.username}
      password: ${wp.datasource.password}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wp.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      wp:
        mapper: debug
        service: info
        controller: info

wp:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: scour
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: Authorization
  alioss:
    endpoint: ${wp.alioss.endpoint}
    access-key-id: ${wp.alioss.access-key-id}
    access-key-secret: ${wp.alioss.access-key-secret}
    bucket-name: ${wp.alioss.bucket-name}
