wp:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: wind_power
    username: scour
    password: 123456
  alioss:
    endpoint: http://oss-cn-beijing.aliyuncs.com
    access-key-id: scour
    access-key-secret: scour
    bucket-name: scour

